### ISSUE TITLE
Add Javascript to update grain URL

### ISSUE THREAD

**Issue by paulproteus** [liamzdenek/phabricator-sandstorm#14]
Quoth the Sandstorm docs:

> By default, when someone interacts with a grain, the URL and page title stay fixed at the grain URL and default grain title. This is because Sandstorm apps runs in an IFRAME, so the top-level URL and title are not automatically synchronized as the user navigates within your app. You can postMessage to the Sandstorm shell to ask it to update the URL in the address bar with the following code snippet:

More info here: https://docs.sandstorm.io/en/latest/developing/path/#updating-the-url-page-title-from-your-app

**Comment by paulproteus** [comment]
FWIW I'm using the SPK from https://github.com/liamzdenek/phabricator-sandstorm/releases/tag/3 .

This is super fun to use, honestly! Thanks so much for working on it!

**Comment by liamzdenek** [comment]
resolved in ee5e8fde533bac078d449f3a40405e85b015b1e1
