### ISSUE TITLE
Consider URL-decoding the X-Sandstorm-Username header

### ISSUE THREAD

**Issue by zarvox** [liamzdenek/phabricator-sandstorm#3]
When I log in as the "Alice Dev Admin" test user, I see something like this for my profile:

![screenshot1](https://cloud.githubusercontent.com/assets/307325/18360336/755ee93c-75b2-11e6-8c57-97fabc38bca3.png)

We should probably url-decode the %20's.  Sandstorm guarantees that the header contains url-encoded UTF-8.

**Comment by liamzdenek** [comment]
Resolved in c0f7490187d0885ed213ab7eb2cb8e14c66fdc13
