### ISSUE TITLE
Migrations should be datestamped

### ISSUE THREAD

**Issue by zarvox** [liamzdenek/phabricator-sandstorm#7]
`.sandstorm/migrations/ss-init-patch.sql` should be datestamped like the other phabricator migrations so that it gets run at the same point in the migration series regardless of what version of phabricator the package is running.

This may become important when upstream releases an update with a new migration - we want the resulting databases from a grain created with phabricator-sandstorm-0 and phabricator-sandstorm-1 to have applied exactly the same migrations in exactly the same order.

**Comment by liamzdenek** [comment]
This will be a breaking change. That's not a problem, as this is still "pre-release." I'm just stating.

**Comment by liamzdenek** [comment]
Resolved in 98183d0d4543d35f9e937e6f88e5823c57dc386f
