### ISSUE TITLE
Link Sandstorm package to publisher's keybase key with signing statement

### ISSUE THREAD

**Issue by zarvox** [liamzdenek/phabricator-sandstorm#8]
(this is not urgent, but should probably happen before the first non-prerelease)

Right now when you go to install the Phabricator package, you see the following:

![install-screenshot](https://cloud.githubusercontent.com/assets/307325/18450110/80f0b7f8-78e6-11e6-9ab0-c47c225d8b70.png)

Since the prereleases already include a detached signature, it'd be nice if we made use of Sandstorm's keybase integration so that Sandstorm can show the author information right in the UI at package install time. :)

https://docs.sandstorm.io/en/latest/developing/publishing-apps/#verify-your-identity describes the process through which you can GPG-sign a statement that you produced a particular package.  This allows Sandstorm (via [keybase integration](https://sandstorm.io/news/2015-11-12-authenticated-app-packages)) to show the packager's name and other Keybase-provided identity information.

**Comment by liamzdenek** [comment]
Resolved in 2b8020cae098ae9c49ae8946dd5dd5938a32ee76
